#!/bin/bash
# Quick Start Commands for Shri Ganpati E-Commerce Platform

echo "🚀 Shri Ganpati E-Commerce Platform - Quick Start Guide"
echo "======================================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 BACKEND SETUP${NC}"
echo "════════════════════════════════════════"
echo ""
echo "1. Install Backend Dependencies"
echo -e "   ${YELLOW}cd backend${NC}"
echo -e "   ${YELLOW}npm install${NC}"
echo ""
echo "2. Create Admin & Worker Accounts"
echo -e "   ${YELLOW}npm run create-admin${NC}"
echo ""
echo "3. (Optional) Seed Sample Orders"
echo -e "   ${YELLOW}npm run seed-orders${NC}"
echo ""
echo "4. Start Backend Server"
echo -e "   ${YELLOW}npm start${NC}         (Production)"
echo -e "   ${YELLOW}npm run dev${NC}       (Development)"
echo ""
echo -e "${GREEN}✅ Backend runs on: http://localhost:5000${NC}"
echo ""

echo -e "${BLUE}📋 FRONTEND SETUP${NC}"
echo "════════════════════════════════════════"
echo ""
echo "1. Install Frontend Dependencies"
echo -e "   ${YELLOW}cd frontend${NC}"
echo -e "   ${YELLOW}npm install${NC}"
echo ""
echo "2. Start Frontend Dev Server"
echo -e "   ${YELLOW}npm run dev${NC}"
echo ""
echo -e "${GREEN}✅ Frontend runs on: http://localhost:5173${NC}"
echo ""

echo -e "${BLUE}🔑 LOGIN CREDENTIALS${NC}"
echo "════════════════════════════════════════"
echo ""
echo "👨‍💼 Admin Account"
echo "   Email:    admin@ganpati.com"
echo "   Password: admin123"
echo ""
echo "👷 Worker Account"
echo "   Email:    worker@ganpati.com"
echo "   Password: worker123"
echo ""
echo -e "${YELLOW}Access: Staff Login button in footer${NC}"
echo ""

echo -e "${BLUE}📱 FEATURE ACCESS${NC}"
echo "════════════════════════════════════════"
echo ""
echo "👤 User (Regular Customer)"
echo "   - Browse Products"
echo "   - Shopping Cart"
echo "   - Checkout & Payment"
echo "   - Order History"
echo "   - Address Management"
echo ""
echo "👨‍💼 Admin"
echo "   - Product Management (Add/Edit/Delete)"
echo "   - Inventory Management (Table View)"
echo "   - Banner Management"
echo "   - Staff Login: admin@ganpati.com / admin123"
echo ""
echo "👷 Worker"
echo "   - Orders Processing"
echo "   - Inventory Tracking"
echo "   - Delivery Management"
echo "   - Order Status Updates"
echo "   - Staff Login: worker@ganpati.com / worker123"
echo ""

echo -e "${BLUE}🔧 USEFUL COMMANDS${NC}"
echo "════════════════════════════════════════"
echo ""
echo "Backend Commands:"
echo -e "   ${YELLOW}npm start${NC}              - Start backend"
echo -e "   ${YELLOW}npm run dev${NC}            - Start with nodemon"
echo -e "   ${YELLOW}npm run create-admin${NC}   - Create admin/worker"
echo -e "   ${YELLOW}npm run seed-orders${NC}    - Add sample orders"
echo ""
echo "Frontend Commands:"
echo -e "   ${YELLOW}npm run dev${NC}            - Start dev server"
echo -e "   ${YELLOW}npm run build${NC}          - Build for production"
echo -e "   ${YELLOW}npm run preview${NC}        - Preview production build"
echo ""

echo -e "${BLUE}📚 DOCUMENTATION${NC}"
echo "════════════════════════════════════════"
echo ""
echo -e "   ${YELLOW}SETUP.md${NC}                    - Complete setup guide"
echo -e "   ${YELLOW}README.md${NC}                   - Full project documentation"
echo -e "   ${YELLOW}IMPLEMENTATION_CHECKLIST.md${NC} - Feature checklist"
echo ""

echo -e "${BLUE}🌐 BROWSER ACCESS${NC}"
echo "════════════════════════════════════════"
echo ""
echo -e "Frontend: ${GREEN}http://localhost:5173${NC}"
echo -e "API:      ${GREEN}http://localhost:5000${NC}"
echo ""

echo -e "${BLUE}⚠️  TROUBLESHOOTING${NC}"
echo "════════════════════════════════════════"
echo ""
echo "If backend won't start:"
echo "   1. Check if MongoDB is running"
echo "   2. Verify .env file has DB_URI"
echo "   3. Check if port 5000 is available"
echo ""
echo "If frontend API calls fail:"
echo "   1. Ensure backend is running"
echo "   2. Check CORS is enabled"
echo "   3. Verify JWT tokens are valid"
echo ""
echo "If no orders showing in worker dashboard:"
echo "   1. Run: npm run seed-orders"
echo "   2. Refresh the page"
echo "   3. Check database connection"
echo ""

echo -e "${GREEN}════════════════════════════════════════${NC}"
echo -e "${GREEN}🎉 You're all set! Happy coding!${NC}"
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo ""
